Repository lightspeeddevelopment/lsx-business-directory, pull requests merged in 2020-03, with the labels that each got.

#16 Phase-1/add/5 - Configure Settings page for General and Search settings
  classes/class-core.php
  classes/class-setup.php
Labels: enhancement

#21 Phase-1/add/9 - Verify the single template works, and pull through the new custom fields
  assets/css/lsx-business-directory-admin-rtl.css
  assets/css/lsx-business-directory-admin.css
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/lsx-starter-plugin-rtl.css
  assets/css/lsx-starter-plugin.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/maps/lsx-business-directory.css.map
  assets/css/maps/lsx-starter-plugin-admin.css.map
  assets/css/maps/lsx-starter-plugin.css.map
  assets/css/scss/lsx-business-directory-admin.scss
  assets/css/scss/lsx-business-directory.scss
  assets/css/scss/lsx-starter-plugin.scss
  assets/js/lsx-business-directory-admin.min.js
  assets/js/lsx-business-directory.min.js
  assets/js/lsx-starter-plugin-admin.min.js
  assets/js/lsx-starter-plugin.min.js
  assets/js/src/lsx-business-directory-admin.js
  assets/js/src/lsx-business-directory.js
  classes/class-core.php
  classes/class-frontend.php
  classes/class-setup.php
  includes/functions.php
  includes/template-tags.php
  package-lock.json
  package.json
  templates/archive-business-directory.php
  templates/archive-custom-post-type.php
  templates/content-custom-post-type.php
  templates/single-business-directory.php
  templates/single-custom-post-type.php
Labels: enhancement

#23 Phase-1/add/7 - Verify the default and search grid and list layouts work on the post type archive
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  classes/class-core.php
  classes/class-frontend.php
  classes/class-integrations.php
  includes/functions.php
  includes/template-tags.php
  templates/archive-business-directory.php
  templates/single-col-business.php
  templates/single-row-business.php
Labels: enhancement

#24 Phase 1/fix/lsx coding standards
  classes/class-admin.php
  classes/class-business-directory.php
  classes/class-core.php
  classes/class-integrations.php
  classes/class-setup.php
  includes/functions.php
  templates/archive-business-directory.php
  templates/single-business-directory.php
  templates/single-col-business.php
  templates/single-row-business.php
Labels: enhancement

#26 Phase 1/add/6 - Add in the functions to connect the search settings to the LSX Search filters
  classes/class-admin.php
  classes/class-integrations.php
  classes/integrations/class-lsx-search.php
  templates/archive-business-directory.php
Labels: enhancement

#28 Added in the get the archive filter to fix the titles.
  classes/class-frontend.php
Labels: enhancement

#30 Phase 1/add/banners - Single Listing Banners
  classes/admin/class-banners.php
  classes/class-admin.php
  classes/class-business-directory.php
  classes/class-frontend.php
  classes/frontend/class-banners.php
  classes/integrations/class-lsx-search.php
  templates/single-business-directory.php
Labels: enhancement, ready-to-merge

#32 Phase 1/fix/single banners
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_banners.scss
  assets/css/scss/lsx-business-directory.scss
  classes/class-business-directory.php
  classes/frontend/class-banners.php
  includes/template-tags.php
  templates/single-business-directory.php
Labels: bug, enhancement

#37 Phase 1/add/search banners
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_banners.scss
  classes/admin/class-banners.php
  classes/class-frontend.php
  classes/frontend/class-banners.php
  classes/integrations/class-lsx-search.php
  includes/getters.php
  vendor/CMB2/init.php
Labels: enhancement

#38 Phase-1/fix/27 - When selecting and enquiry form, the button does not show on the single listing
  classes/class-core.php
  classes/class-frontend.php
  classes/frontend/class-enquiry.php
  includes/functions.php
  templates/single-business-directory.php
Labels: bug, enhancement

#39 Phase 1/add/taxonomy featured images
  classes/admin/class-placeholders.php
  classes/admin/class-term-thumbnail.php
  classes/class-admin.php
  classes/class-post-type.php
  classes/class-setup.php
  classes/setup/class-business-directory.php
  includes/getters.php
  includes/template-tags.php
Labels: enhancement

#41 Phase 1/add/placeholders
  assets/img/placeholder-1920x600.jpg
  assets/img/placeholder-350x350.jpg
  assets/img/placeholder-360x168.jpg
  assets/img/placeholder-750x350.jpg
  classes/admin/class-archive.php
  classes/admin/class-placeholders.php
  classes/admin/class-single.php
  classes/admin/class-term-thumbnail.php
  classes/class-admin.php
  includes/getters.php
  includes/helpers.php
  includes/template-tags.php
  templates/single-business-directory.php
  templates/single-col-business.php
  templates/single-row-business.php
Labels: enhancement

#43 Phase-1/add/slugs - Slug changes to archives and taxonomies.
  assets/css/lsx-business-directory-admin-rtl.css
  assets/css/lsx-business-directory-admin.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory-admin.scss
  classes/admin/class-banners.php
  classes/class-admin.php
  classes/class-frontend.php
  classes/frontend/class-banners.php
  classes/frontend/class-template-redirects.php
  classes/integrations/class-lsx-search.php
  classes/setup/class-business-directory.php
  package-lock.json
  package.json
  templates/single-business-directory.php
  templates/single-col-business.php
  templates/single-row-business.php
Labels: enhancement

#44 Phase 1/fix/35 - CMB2 Tabbed Theme
  assets/css/lsx-business-directory-admin-rtl.css
  assets/css/lsx-business-directory-admin.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_cmb_tabbed_theme.scss
  assets/css/scss/lsx-business-directory-admin.scss
  classes/admin/class-archive.php
  classes/admin/class-cmb-tab-field.php
  classes/admin/class-settings-theme.php
  classes/admin/class-single.php
  classes/class-admin.php
  classes/integrations/class-lsx-search.php
Labels: enhancement

#45 Phase-1/add/styling - CSS adjustments to match closer to designs.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  templates/archive-business-directory.php
  templates/single-col-business.php
  templates/single-row-business.php
  templates/taxonomy-business-directory.php
Labels: enhancement

#46 Phase-1/add/single styling - Styling of single template to look like designs.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  templates/single-business-directory.php
Labels: enhancement

#47 Phase 1/add/related listings
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_related_listings.scss
  assets/css/scss/lsx-business-directory.scss
  assets/js/lsx-business-directory.min.js
  assets/js/src/lsx-business-directory.js
  classes/class-frontend.php
  classes/frontend/class-widget.php
  includes/template-tags.php
  templates/single-business-directory.php
Labels: enhancement

#48 Phase-1/add/skype_whatsapp - Added Skype and Whatsapp buttons in Single template.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  templates/single-business-directory.php
Labels: enhancement

#49 Phase-1/add/social_icons - Added new fields for Social networking in backend and icon links in Single.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  classes/setup/class-business-directory.php
  templates/single-business-directory.php
Labels: enhancement

#50 Phase 1/fix/36 - Field Label bugs
  classes/frontend/class-widget.php
  classes/integrations/class-lsx-search.php
  includes/getters.php
  templates/single-business-directory.php
Labels: bug

#51 Phase 1/fix/36 2 bugherd fixes - plugins settings layout + placeholder settings
  assets/css/lsx-business-directory-admin-rtl.css
  assets/css/lsx-business-directory-admin.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/scss/_cmb_edit_terms.scss
  assets/css/scss/_cmb_tabbed_theme.scss
  assets/css/scss/lsx-business-directory-admin.scss
  includes/getters.php
  includes/helpers.php
Labels: bug

#54 Phase 1/fix/36 - 3 - Placeholder and Settings Labels
  classes/admin/class-banners.php
  classes/admin/class-placeholders.php
  classes/class-frontend.php
  classes/frontend/class-placeholders.php
  classes/integrations/class-lsx-search.php
  includes/functions.php
  includes/getters.php
  includes/helpers.php
  includes/template-tags.php
Labels: bug

#52 Phase-1/add/styling_bugs - touch ups to closely match designs
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  classes/class-integrations.php
  classes/frontend/class-enquiry.php
  classes/frontend/class-widget.php
  classes/integrations/class-lsx-gravity-forms.php
  classes/integrations/class-lsx-ninja-forms.php
  classes/integrations/class-lsx-wpforms.php
  templates/single-business-directory.php
  templates/single-col-business.php
  templates/single-row-business.php
Labels: enhancement

#55 Phase-1/add/archives_styling - Archive pages styling to match designs closer.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  templates/single-col-business.php
  templates/single-row-business.php
Labels: enhancement

#59 Phase 1/fix/archives bugherd - Fixing the search layout.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_lsx_blog_customizer.scss
  assets/css/scss/lsx-business-directory.scss
  classes/class-frontend.php
  templates/single-col-business.php
Labels: bug

#58 Phase-1/fix/bugs - Bugherd tasks addressed
  assets/css/lsx-business-directory-admin-rtl.css
  assets/css/lsx-business-directory-admin.css
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory-admin.css.map
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_cmb_tabbed_theme.scss
  assets/css/scss/lsx-business-directory.scss
Labels: bug

#62 Phase 1/fix/archive row styling
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  templates/single-row-business.php
Labels: bug, enhancement

#61 Phase-1/fix/archive_fixes - Bugherd for archive pages.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
  templates/single-col-business.php
  templates/single-row-business.php
Labels: bug

#63 Phase-1/fix/list_layout - List layout font size changes.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/lsx-business-directory.scss
Labels: bug

#64 Phase-1/add/cleanupcss - Cleaning up CSS
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_archive.scss
  assets/css/scss/_archive_col.scss
  assets/css/scss/_archive_row.scss
  assets/css/scss/_general.scss
  assets/css/scss/_single.scss
  assets/css/scss/_variables.scss
  assets/css/scss/lsx-business-directory.scss
  assets/js/lsx-business-directory.min.js
  assets/js/src/lsx-business-directory.js
Labels: enhancement

#65 Phase-1/fix/cssbugs - Few last bugs on bugherd related to styles on Single.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_archive_col.scss
  assets/css/scss/_archive_row.scss
  assets/css/scss/_single.scss
Labels: bug

#66 Phase-1/fix/singlecssbugs - Single styling touchup.
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_single.scss
  templates/single-business-directory.php
Labels: bug

#68 Fix/options tab persistence
  classes/admin/class-settings-theme.php
  vendor/CMB2/includes/CMB2_Options_Hookup.php
Labels: enhancement, ready-to-merge

#69 Removing the `using-gutenberg` body class when the listing is using blocks
  changelog.md
  changelog.txt
  classes/class-frontend.php
Labels: bug, ready-to-merge

#70 Fix/bugherd 41+47
  assets/css/lsx-business-directory-rtl.css
  assets/css/lsx-business-directory.css
  assets/css/maps/lsx-business-directory.css.map
  assets/css/scss/_archive_col.scss
  assets/css/scss/_single.scss
  changelog.md
  templates/single-business-directory.php
  templates/single-col-business.php
Labels: bug

#72 Add/slug translations
  changelog.md
  classes/admin/class-translations.php
  classes/class-admin.php
  classes/class-core.php
  classes/setup/class-business-directory.php
  includes/functions.php
  includes/template-tags.php
  vendor/CMB2/init.php
Labels: enhancement
